In [6]:
import networkx as nx
import numpy as np

In [7]:
G = nx.barabasi_albert_graph(5,2)

In [8]:
adj = nx.convert_matrix.to_numpy_array(G)

In [11]:
D = np.diag(np.sum(adj,axis=1))

In [14]:
L = D-adj

In [15]:
L

array([[ 4., -1., -1., -1., -1.],
       [-1.,  3.,  0., -1., -1.],
       [-1.,  0.,  1.,  0.,  0.],
       [-1., -1.,  0.,  2.,  0.],
       [-1., -1.,  0.,  0.,  2.]])

In [27]:
(evl,evs) = np.linalg.eig(L)

In [28]:
evs.shape

(5, 5)

In [29]:
evs[:,0]

array([ 0.89442719, -0.2236068 , -0.2236068 , -0.2236068 , -0.2236068 ])

In [30]:
evs[:,1]

array([-0.4472136, -0.4472136, -0.4472136, -0.4472136, -0.4472136])

In [31]:
np.sum(evs[0,:]*evs[4,:])

-1.3877787807814462e-16

In [32]:
evl

array([5., 0., 4., 1., 2.])

In [33]:
evs1 = np.ones((5,5))

In [34]:
evs1[0,0] = 0
evs1[2,2] = 0
evs1[3,3] = 0
evs1[4,4] = 0

In [35]:
evs1

array([[0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [36]:
np.diag(evl)

array([[5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 2.]])

In [37]:
Q = evs1
D = np.diag(evl)

In [41]:
L1 = np.dot(np.dot(Q,D),np.linalg.inv(Q))

In [43]:
(evl,evs) = np.linalg.eig(L1)

In [49]:
evs[0,:]

array([ 4.47213595e-01, -1.36054908e-15,  5.00000000e-01,  5.00000000e-01,
       -5.00000000e-01])

In [48]:
evl

array([-4.4408921e-15,  5.0000000e+00,  4.0000000e+00,  2.0000000e+00,
        1.0000000e+00])

In [50]:
L1

array([[ 0.,  7., -4., -1., -2.],
       [-5., 12., -4., -1., -2.],
       [-5.,  8.,  0., -1., -2.],
       [-5., 11., -4.,  0., -2.],
       [-5., 10., -4., -1.,  0.]])